version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  target-branch: mf-cs-documentation
  versioning-strategy: increase-if-necessary
