ruby '>= 3.1'
source 'https://rubygems.org'

gem 'benchmark'
gem 'bigdecimal'
gem 'base64'
gem 'csv'
gem 'logger'
gem 'mutex_m'
gem 'ostruct'
gem 'rdoc'

# Middleman
gem 'middleman', '~> 4.6.3'
gem 'middleman-syntax', '~> 3.2'
gem 'middleman-autoprefixer', '~> 3.0'
gem 'middleman-sprockets', '~> 4.1'
gem 'middleman-data_source'
gem 'rouge', '~> 3.21'
gem 'redcarpet', '~> 3.6.0'
gem 'nokogiri', '~> 1.19'
gem 'sass'
gem 'webrick'
